AlbumStore/Controllers/AlbumController.cs
using MartinJRufino_20210227.Manager.Interfaces;
using MartinJRufino_20210227.Model.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MartinJRufino_20210227.Controllers
{
    [ApiController]
    [Route("")]
    [Route("[controller]")]
    public class AlbumController : Controller
    {
        private readonly IDomainManager _domainManager;
        public AlbumController(ILogger<AlbumController> logger, IDomainManager domainManager)
        {
            _domainManager = domainManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetAlbums()
        {

            return View("Index", await _domainManager.GetAllAlbums());
        }
    }
}

AlbumStore/Controllers/CommentController.cs
using MartinJRufino_20210227.Manager.Interfaces;
using MartinJRufino_20210227.Model.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MartinJRufino_20210227.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class CommentController : Controller
    {
        private readonly IDomainManager _domainManager;
        public CommentController(ILogger<CommentController> logger, IDomainManager domainManager)
        {
            _domainManager = domainManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetComments(int postId)
        {
            return View("Comment", await _domainManager.GetComments(postId));
        }
    }
}

AlbumStore/Controllers/PhotoController.cs
using MartinJRufino_20210227.Manager.Interfaces;
using MartinJRufino_20210227.Model.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MartinJRufino_20210227.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PhotoController : Controller
    {
        private readonly IDomainManager _domainManager;
        public PhotoController(ILogger<PhotoController> logger, IDomainManager domainManager)
        {
            _domainManager = domainManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetPhotos(int albumId)
        {
            return View("Photo", await _domainManager.GetPhotos(albumId));
        }
    }
}

AlbumStore/Views/Album/Index.cshtml
@model MartinJRufino_20210227.Model.Response.AlbumResponse

@{
    ViewData["Title"] = "View";
}

<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Id</th>
            <th>Titulo</th>
            <th>Detalle</th>
        </tr>
        @foreach (var item in Model.albumLst)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.title</td>
                <td><input type="button" value="Detalle" onclick="location.href='@Url.Action("GetPhotos", "Photo", new { albumId = item.id })'" /></td>
            </tr>
        }
    </tbody>
</table>

AlbumStore/Views/Comment/Comment.cshtml
@model MartinJRufino_20210227.Model.Response.CommentResponse

@{
    ViewData["Title"] = "Comment";
}
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Mensaje</th>
        </tr>
        @foreach (var item in Model.commentLst)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.name</td>
                <td>@item.email</td>
                <td>@item.body</td>
            </tr>
        }
    </tbody>
</table>

AlbumStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AlbumStore/Views/Photo/Photo.cshtml
@model MartinJRufino_20210227.Model.Response.PhotoResponse

@{
    ViewData["Title"] = "View";
}

<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Id</th>
            <th>Titulo</th>
            <th>Imagen</th>
            <th>Thumbnail</th>
            <th>Detalle</th>
        </tr>
        @foreach (var item in Model.photoLst)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.title</td>
                <td><img src="@item.url" /></td>
                <td><img src="@item.thumbnailUrl" /></td>
                <td><input type="button" value="Detalle" onclick="location.href='@Url.Action("GetComments", "Comment", new { postId = item.id })'" /></td>
            </tr>
        }
    </tbody>
</table>

AlbumStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AlbumStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Album" asp-action="Index">AlbumStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AlbumStore - <a asp-area="" asp-controller="Album" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>